version: "3.5"

services:
  redis:
    image: 'redis:6.2-alpine'
    volumes:
       - ./.docker/redis:/data
    ports:
      - '6379:6379'
    restart: unless-stopped
    networks:
      - jobs-manager-network
  manager:
    build:
      context: .
      dockerfile: ./infra/manager/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
      - example
    volumes:
      - ./:/app
    networks:
      - jobs-manager-network
  example:
    build:
      context: .
      dockerfile: ./infra/example/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./:/app
    networks:
      - jobs-manager-network
networks: 
    jobs-manager-network:
      driver: bridge