version: "3.5"

services:
  redis:
    image: 'redis:6.2-alpine'
    volumes:
       - ./.docker/redis:/data
    ports:
      - '6379:6379'
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass admin
