# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "./infra/example/tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./infra/example/tmp/main ./cmd/example"
# Binary file yields from `cmd`.
bin = "infra/example/tmp/main"
# Watch these files.
include_file = ["config.json"]

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true